### ISSUE TITLE
Some of the switches in settings are not working

### ISSUE THREAD

**Issue by McArdellje** [SeinopSys/Derpi-NewTab#10]
The state of the switches aren't saved (except "Show EQG-related") and don't effect the results
The effected switches are
- Exclude unselected tags
- Show EQG-related images
- Resolution cap
Resolution cap also doesn't apply even though it defaults to on

**Comment by SeinopSys** [comment]
Good catch, truthfully I rarely ever change these so I never realized they ever got broken, Thank you!

I'll have a look at #11 as well and if it's easy enough I'll do another release that includes both of these.
