### ISSUE TITLE
Trailing ampersands cause lots of wallpapers to not show up

### ISSUE THREAD

**Issue by rctgamer3** [SeinopSys/Derpi-NewTab#4]
https://github.com/SeinopSys/Derpi-NewTab/blob/master/derpinewtab/js/settings.js#L44
Clicked all tags, search query is `wallpaper && (safe || questionable || explicit || semi-grimdark || grimdark || grotesque) && ` but the last two && cause it to return no results on derpibooru. Removed these trailing ampersands and wallpapers instantly started showing.

**Comment by SeinopSys** [comment]
Thank you for reporting the issue, I've released v2.3.1 on both the CWS and AMO which contains a fix for this.
