### ISSUE TITLE
Image failed to load.

### ISSUE THREAD

**Issue by Waterspark63** [SeinopSys/Derpi-NewTab#5]
Every time I try to change the tags on Derpi New Tab, I get 'Image failed to load, either the image is no longer available, or extension is broken.' I've tried to reinstall the extension, that didn't help. Any ideas, and the filters are not the issue.

**Comment by SeinopSys** [comment]
Sorry about that, I'll look into this in a couple hours.

**Comment by Waterspark63** [comment]
Thank you, I found a slight work around, I switched to trixiebooru, and it kinda works, still sometimes break, but the main issue still appears.

**Comment by SeinopSys** [comment]
Do you see any errors in the browser console? (Ctrl+Shift+I)

**Comment by Waterspark63** [comment]
No, not seeing any, heres a image to make sure im looking in the right place

https://postimg.cc/image/aja9uvay3/

**Comment by SeinopSys** [comment]
You are indeed looking in the right place. Please switch over to the
network tab and check if there are any red entries in the list,
particularly the one that says "search.json" in the first column. If you
find that, click it, switch to the preview tab in the panel that opens and
send an image of that.

**Comment by SeinopSys** [comment]
Actually, something else that would be helpful - if you feel that what I said earlier was too complicated - you can right-click the "Open search page" button and copy the link's address, then send it here. Opening that page should show you images, so if there's none there that would be a good starting point. I cannot reproduce the issue on my end, so I'll need your help to fix it.

**Comment by Waterspark63** [comment]
It seems to of stopped... I don't know if it was temporary or what but yeah... 
Its working now... And sorry, haven't been on GH/email in a while

**Comment by SeinopSys** [comment]
Glad it's all sorted now!
