### ISSUE TITLE
Unable to get current api key and filter or manually set api key

### ISSUE THREAD

**Issue by McArdellje** [SeinopSys/Derpi-NewTab#9]
I don't know how to fix the latter issue but to fix the former you can change line 318 of `settings.js` from
``fetch(`https://${fetchDomain}/registration/edit`, {`` to ``fetch(`https://${fetchDomain}/registrations/edit`, {``
and that allows you to use the "Get Current & Apply" button again

**Comment by SeinopSys** [comment]
Thanks for reporting this, I somehow completely failed to handle that input field so far. The release with the fix will be pushed to CWS & AMO soon.
